name: token_storage
description: Token storage for both mobile and web

verison: 0.0.1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^3.3.1+1